"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from "@/components/Navigation";
import {RecoilRoot} from "recoil";
import Script from "next/script";
import Head from 'next/head';
import {useParams} from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const parameter = useParams()
  return (
      <html lang="en">
      <body className={inter.className}>
      <RecoilRoot>
          {/*{parameter == "chat"? (<Navigation />):(<Navigation>{children}</Navigation>)}*/}
            <Navigation>
                {children}
            </Navigation>
      </RecoilRoot>
      </body>
      </html>
  )
}
